/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { UserCreateNestedManyWithoutProjectsInput } from "./UserCreateNestedManyWithoutProjectsInput";
import { Type } from "class-transformer";
import { EnumProjectStatus } from "./EnumProjectStatus";
import { TaskCreateNestedManyWithoutProjectsInput } from "./TaskCreateNestedManyWithoutProjectsInput";
@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  members?: UserCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    enum: EnumProjectStatus,
    isArray: true,
  })
  @IsEnum(EnumProjectStatus, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumProjectStatus], {
    nullable: true,
  })
  status?: Array<"Inactive" | "Active" | "Closed">;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutProjectsInput;
}
export { ProjectCreateInput };
