/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { UserUpdateManyWithoutProjectsInput } from "./UserUpdateManyWithoutProjectsInput";
import { Type } from "class-transformer";
import { EnumProjectStatus } from "./EnumProjectStatus";
import { TaskUpdateManyWithoutProjectsInput } from "./TaskUpdateManyWithoutProjectsInput";
@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  members?: UserUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    enum: EnumProjectStatus,
    isArray: true,
  })
  @IsEnum(EnumProjectStatus, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumProjectStatus], {
    nullable: true,
  })
  status?: Array<"Inactive" | "Active" | "Closed">;

  @ApiProperty({
    required: false,
    type: () => TaskUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => TaskUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => TaskUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  tasks?: TaskUpdateManyWithoutProjectsInput;
}
export { ProjectUpdateInput };
